### PR TITLE
from libextract import extract

### PR DESCRIPTION
**Pull request by bofm**
"libextract.api" is too deep for a one-function library.

### CODE REVIEW

**Comment by rodricios** [comment]
:sweat_smile: The idea was that we would have more extractors, eventually... 

I want to wait on @eugene-eeo to hear what he thinks, as we were just talking about possibly including a supervised extractor; such a change would qualify the point of having an `api` submodule.

**Comment by eugene-eeo** [comment]
Sorry that I somehow missed this out. Ok so what is expected of an `api` submodule is so that we can keep the version consistent across both the `setup.py` file and the source code itself. Also it makes importing the library faster as the initial import doesn't do anything and prevents us from falling into traps like circular dependencies.

It also forces the user to be more explicit and we can control what is provided to them if they do a star-import, e.g. `from libextract import *`.

**Comment by bofm** [comment]
Ok, `libextract.api` is supposed to be used for the imports. The other modules are considered internal, right? Doesn't the `.api` look redundant from the usage perspective?

**Comment by rodricios** [comment]
@bofm: IMHO, it does appear redundant, usage wise. I borrowed @eugene-eeo's convention of having a `api` submodule, who in turn borrowed it from Wesley Beary(?). 

I can say that it does make intuitive sense (to me) to have an `api` module for end-user-application stuff - personally, it acts sort of like a mental self-guidance tip: "Okay @rodricios, `api` is for API, so program accordingly...". 

On the other hand, top-level `libextract` can act as an implied `api` submodule, and I believe it's meant to be that. 

I'm split between the two options.

**Comment by eugene-eeo** [comment]
The main advantages of having the `api` submodule is:
- **Efficiency**\- if certain imports are not needed by the user, they are not implicitly imported when you import the main module.
- **Separation of Concerns**\- Without trying to throw buzzwords around, what we get from having a separate module just for the end-user-facing interface makes it easier to remind ourselves of what we are exposing. Also, the index module (`__init__.py`) should be blank and just filled with metadata in my opinion.
- **No Circular Dependency**\- We are guaranteed to not have any circular dependencies if we are just importing from other modules in the `api` submodule, instead of having one big index module that may cause some problems during runtime dependency resolution.

Also this convention is used by Brandon Rhode's [Skyfield](https://github.com/skyfielders/python-skyfield/) library. You can see his [talk](https://www.youtube.com/watch?v=FVEEndIwOSA) on the design decisions behind a separate `api` submodule. To an extent the `api` submodule may be a more philosophical thing- you do `from _.api import _` instead of `from _ import _`.

**Pull request closed without merging**
