### PR TITLE
New architecture 

### PR DESCRIPTION
**Pull request by rodricios**

### CODE REVIEW

**Comment by eugene-eeo** [comment]
Might seem like a bummer but what about flowlib integration? Also a dependency injection framework called [injector](https://github.com/alecthomas/injector) could be integrated as well, it looks really nice to me and we can cut down on writing our own implementation.

**Comment by rodricios** [comment]
Can you describe where [injector](https://github.com/alecthomas/injector) would be used? Also, I'm all for integrating flowlib, but let's work on that once this branch is merged - it would be a pretty big jump between versions if not.

**Comment by eugene-eeo** [comment]
:+1: injector (could) be packaged alongside with libextract so that users can do dependency injection, i.e. so they don't have to throw closures everywhere and can test their functions nicely.

**Comment by rodricios** [comment]
Great, I'm simplifying the README, push, then merge, and we can get to working on a next release.

**Comment by rodricios** [comment]
Awesome, merging now.

**Pull request merged**
